### PR TITLE
feat: add badges to README.md

### LINKED ISSUE #86: [Feature] Add badges to the README
### Feature

Because swag

### PR DESCRIPTION
**Pull request by AirOne01**
Closes #86

### CODE REVIEW

**Comment by barthofu** [comment]
Related to https://github.com/barthofu/tscord/pull/87#issuecomment-1282156583, we should find another way to display the latest version of the template in a badge.

Maybe the easiest solution is to make a manual and custom badge that we update at each version, and try to automate it afterwards?

**Comment by barthofu** [comment]
Another thing: the `Deploy` badge is not usefull as the template is not intended to be deployed. The github action exists for users that will develop their own bots.

**Comment by AirOne01** [comment]
True, i'm just tired. For the template version, we could use a gist simply.

**Comment by barthofu** [comment]
> I suggest we cancel this idea and remove it. Do you approve ?

The other badges are ok, we could at least keep them and see later for the version badge?

**Comment by barthofu** [comment]
ok so @AirOne01 

some changes:
- [shields.io](https://shields.io/) has a badge for the latest github release version, exactly what we wanted!
- added a custom badge 'bout the number of sponsors we have on the project
- customized and uniformised the overall style to match the logo colors

### Results:
image

are you ok with this?

**Comment by AirOne01** [comment]
> ok so @AirOne01 
> 
> 
> 
> some changes:
> 
> - [shields.io](https://shields.io/) has a badge for the latest github release version, exactly what we wanted!
> 
> - added a custom badge 'bout the number of sponsors we have on the project
> 
> - customized and uniformised the overall style to match the logo colors
> 
> 
> 
> ### Results:
> 
> image
> 
> 
> 
> are you ok with this?

Yup, sounds good to me !

**Pull request merged**
